export enum GatewayEnvVariableKeys {
  port = 'PORT',
  enableApm = 'ENABLE_APM',
  gatewayJwtToken = 'GATEWAY_JWT_TOKEN',
  jwtToken = 'JWT_TOKEN',
  nodeEnv = 'NODE_ENV',
  secretKeyOne = 'SECRET_KEY_ONE',
  secretKeyTwo = 'SECRET_KEY_TWO',
  clientUrl = 'CLIENT_URL',
  authBaseUrl = 'AUTH_BASE_URL',
  usersBaseUrl = 'USERS_BASE_URL',
  gigBaseUrl = 'GIG_BASE_URL',
  messageBaseUrl = 'MESSAGE_BASE_URL',
  orderBaseUrl = 'ORDER_BASE_URL',
  reviewBaseUrl = 'REVIEW_BASE_URL',
  redisHost = 'REDIS_HOST',
  elasticsearchUrl = 'ELASTIC_SEARCH_URL',
  elasticApmServerUrl = 'ELASTIC_APM_SERVER_URL',
  elasticApmSecretToken = 'ELASTIC_APM_SECRET_TOKEN'
}
